AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  digital-fumi: A web service for delayed messaging.

Globals:
  Function:
    Runtime: nodejs20.x # Node.js 20を使用
    Timeout: 10
    MemorySize: 128
    Environment:
      Variables:
        DYNAMO_TABLE_NAME: !Ref FumiTable
        STATE_MACHINE_ARN: !Ref DeliveryStateMachine

Resources:
  # --- 1. DynamoDB データベース ---
  FumiTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: messageId # メッセージごとのユニークID
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: RecipientStatusIndex # 受信トレイ取得用インデックス
          Projection:
            ProjectionType: ALL
          KeySchema:
            - AttributeName: recipientId
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE

  # --- 2. Step Functions (24時間待機) ---
  DeliveryStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      Definition:
        Comment: "Wait 24 hours and deliver a message"
        StartAt: WaitForDelivery
        States:
          WaitForDelivery:
            Type: Wait
            Seconds: 86400 # 24時間 (86400秒)
            # (テスト用に 'Seconds: 60' などに変更)
            Next: DeliverMessage
          DeliverMessage:
            Type: Task
            Resource: !GetAtt DeliverMessageFunction.Arn
            End: true
      RoleArn: !GetAtt StateMachineRole.Arn

  # --- 3. Lambda関数群 ---
  # L1: 送信
  SendMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/
      Handler: lambda_send.handler
      Policies:
        - DynamoDBCrudPolicy: # DBへの書き込み権限
            TableName: !Ref FumiTable
        - StepFunctionsStartExecutionPolicy: # Step Functionsの開始権限
            StateMachineName: !GetAtt DeliveryStateMachine.Name
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /send
            Method: post
            RestApiId: !Ref FumiApi

  # L2: 配達 (StepFunctionsからキック)
  DeliverMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/
      Handler: lambda_deliver.handler
      Policies:
        - DynamoDBCrudPolicy: # DBのステータス更新権限
            TableName: !Ref FumiTable
      
  # L3: 受信トレイ取得
  GetInboxFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/
      Handler: lambda_getInbox.handler
      Policies:
        - DynamoDBReadPolicy: # DBの読み取り権限
            TableName: !Ref FumiTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /inbox
            Method: get
            RestApiId: !Ref FumiApi

  # --- 4. API Gateway (REST API) ---
  FumiApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'POST, GET, OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'" # 本番環境では要制限

  # --- 5. 必要なIAMロール ---
  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt DeliverMessageFunction.Arn

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${FumiApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"